services:
  backend:
    image: ghcr.io/${REPO}-backend:${TAG}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_MINI_APP_SHORT_NAME: ${TELEGRAM_MINI_APP_SHORT_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      S3_KEY: ${S3_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

  bot:
    image: ghcr.io/${REPO}-bot:${TAG}
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME}
      TELEGRAM_MINI_APP_SHORT_NAME: ${TELEGRAM_MINI_APP_SHORT_NAME}
      BACKEND_BASE_URL: http://backend:8000
      BACKEND_BEARER_TOKEN: ${TELEGRAM_BOT_TOKEN}
      FRONTEND_BASE_URL: ${FRONTEND_BASE_URL}
      S3_KEY: ${S3_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
    depends_on:
      - backend

  frontend:
    image: ghcr.io/${REPO}-frontend:${TAG}
    restart: unless-stopped
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
      VITE_API_PROXY_TARGET: http://backend:8000
    depends_on:
      - backend
